# This is a basic workflow to help you get started with Actions

name: Build and Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  repository_dispatch:
    types: 
      - build-and-deploy


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-website:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup badges dir
        run: |
          mkdir -p .github/badges
      - uses: emibcn/badge-action@v1
        with:
          label: 'status'
          status: 'building'
          color: 'blue'
          path: '.github/badges/status.svg'
        
      # Set up node
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12
        

      # Runs a set of commands using the runners shell
      - name: Build gatsby site
        run: |
          yarn install
          cd web
          yarn install
          yarn build
          
      
          
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1.11
        with:
          publish-dir: web/public
          production-branch: master
          deploy-message: Publish from Github
        env: 
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      
      - uses: emibcn/badge-action@v1
        if: failure()
        with:
          label: 'status'
          status: 'failed'
          color: 'red'
          path: '.github/badges/status.svg'
      - uses: emibcn/badge-action@v1
        if: success()
        with:
          label: 'status'
          status: 'failed'
          color: 'red'
          path: '.github/badges/status.svg'
